# Default image (https://hub.docker.com/_/microsoft-dotnet-sdk)
# Multiarch image, it has both Linux and Windows versions
image: mcr.microsoft.com/dotnet/sdk:8.0

stages:
  - build
  - test

include:
  # NuGet Dependency Scanning
  # https://docs.gitlab.com/ee/user/application_security/dependency_scanning/
  - template: Jobs/Dependency-Scanning.gitlab-ci.yml
  - local: ci/Code-Quality-dotNET.gitlab-ci.yml

# Build model
# (Uses Linux-based runner, because windows tag is NOT specified.)
build_model:
  stage: build
  before_script:
    - dotnet --version
  script:
    - dotnet build TicTacToeGame.Model.Basic
    - dotnet build TicTacToeGame.Persistence.Text
    - dotnet build TicTacToeGame.Persistence.Binary

# Build complete solution
# (Uses Windows-based runner, because windows tag IS specified.)
build_view:
  stage: build
  # Use a Windows Server Core based docker image
  # The default mcr.microsoft.com/dotnet/sdk:8.0 would depend on Windows Nano Server, 
  # which is not enough for us, as it does not containt the desktop packs.
  image: mcr.microsoft.com/dotnet/sdk:8.0-windowsservercore-ltsc2019
  tags: [windows]
  before_script:
    - dotnet --version
  script:
    - dotnet build Safari.sln

# Test
# (Uses Linux-based runner, because windows tag is NOT specified.)
test_model:
  stage: test
  before_script:    
    # Restore NuGet packages to the local .nuget folder (inside the project directory).
    - dotnet restore SafariGame.Test --packages .nuget
  script:
    - > 
      dotnet test SafariGame.Test --no-restore
      --logger:"junit;LogFilePath=../junit/{assembly}-test-result.xml;MethodFormat=Class;FailureBodyFormat=Verbose"
      --collect="XPlat Code Coverage"
    # Install tools for code coverage extraction from Cobertura XML files
    - apt-get update -yqq
    - apt-get install -yqq bc
    - dotnet tool install --tool-path . dotnet-reportgenerator-globaltool
    # Compute code coverage percentage from Cobertura XML files through merging them with ReportGenerator
    # https://github.com/danielpalme/ReportGenerator
    - ./reportgenerator "-reports:$CI_PROJECT_DIR/*/TestResults/*/coverage.cobertura.xml" "-targetdir:report" "-reporttypes:Cobertura"
    - line_rate="$(head -n 3 ./report/Cobertura.xml | sed 'N;N;s/.*line-rate="\([^" ]*\).*/\1/g')"
    - coverage=$(echo "${line_rate} * 100" | bc)
    - 'printf "TOTAL_COVERAGE=%2.2f\n" "$coverage"'
    # Alternatively compute the total coverage through simple summation
    #- chmod +x ./ci/coverage-percentage.sh
    #- ./ci/coverage-percentage.sh .
  # Cache and keep downloaded NuGet dependencies between CI pipelines
  cache:
    # The CI_COMMIT_REF_SLUG is a slug for the branch or tag name,
    # so there will be a separate cache for each branch.
    key: "unittest-$CI_COMMIT_REF_SLUG"
    paths:
      - .nuget
  artifacts:
    paths:
      - ./junit/*test-result.xml
      - ./*/TestResults/*/coverage.cobertura.xml
    reports:      
      # Publish unit test results to GitLab UI
      # https://docs.gitlab.com/ee/ci/testing/unit_test_reports.html
      junit:
        - ./junit/*test-result.xml      
      # Test coverage visualization on GitLab UI
      # https://docs.gitlab.com/ee/ci/testing/test_coverage_visualization.html
      coverage_report:
        coverage_format: cobertura
        path: ./*/TestResults/*/coverage.cobertura.xml
  # Report code coverage for GitLab
  # https://docs.gitlab.com/ee/ci/testing/code_coverage.html
  coverage: '/TOTAL_COVERAGE=(\d+.\d+)/'

